# Generated by Django 4.0.8 on 2022-10-11 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, verbose_name='Название категории')),
            ],
            options={
                'db_table': 'contestsCategory',
            },
        ),
        migrations.CreateModel(
            name='GalleryContests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryContests',
            },
        ),
        migrations.CreateModel(
            name='GalleryNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryNews',
            },
        ),
        migrations.CreateModel(
            name='GalleryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, verbose_name='Название галереи')),
            ],
            options={
                'db_table': 'galleryProject',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10, verbose_name='Язык')),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70, verbose_name='Название категории')),
            ],
            options={
                'db_table': 'projectCategory',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70, verbose_name='Заголовок проекта')),
                ('Description', models.TextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Status', models.CharField(choices=[('В процессе', 'В процессе'), ('Реализованные', 'Реализованные'), ('Не реализованные', 'Не реализованные')], default='В процессе', max_length=20, verbose_name='Выберите Статус')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.projectcategory', verbose_name='Выберите Категория')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language', verbose_name='Выберите Язык')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.FilePathField(verbose_name='Путь картинки')),
                ('Title', models.CharField(max_length=70, verbose_name='Заголовок картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.FilePathField(verbose_name='Путь картинки')),
                ('Title', models.CharField(max_length=70, verbose_name='Заголовок картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='PhotosContests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.FilePathField(verbose_name='Путь картинки')),
                ('Title', models.CharField(max_length=70, verbose_name='Заголовок картинки')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.galleryproject', verbose_name='Галерея')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70, verbose_name='Заголовок новости')),
                ('Discription', models.TextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language', verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70, verbose_name='Заголовок конкурса')),
                ('Discription', models.TextField(verbose_name='Описание')),
                ('Date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.contestscategory', verbose_name='Выберите Категорию')),
                ('Gallery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerycontests', verbose_name='Выберите Галерую')),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.language', verbose_name='Выберите Язык')),
            ],
        ),
    ]
