# Generated by Django 4.0.8 on 2022-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contests',
            old_name='Discription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Discription',
            new_name='Description',
        ),
        migrations.AddField(
            model_name='contests',
            name='Short_Description',
            field=models.CharField(default='', max_length=110, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='Short_Description',
            field=models.CharField(default='', max_length=110, verbose_name='Краткое описание'),
        ),
    ]
