# Generated by Django 4.0.8 on 2022-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_discription_contests_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contests',
            name='Document',
            field=models.FileField(default='', upload_to='', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='contests',
            name='Status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Проведён', 'Проведён'), ('Не Проведён', 'Не Проведён')], default='В процессе', max_length=20, verbose_name='Выберите Статус'),
        ),
        migrations.AlterField(
            model_name='photoscontests',
            name='URL',
            field=models.FileField(upload_to='', verbose_name='Путь картинки'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='URL',
            field=models.FileField(upload_to='', verbose_name='Путь картинки'),
        ),
        migrations.AlterField(
            model_name='photosproject',
            name='URL',
            field=models.FileField(upload_to='', verbose_name='Путь картинки'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Реализован', 'Реализован'), ('Не реализован', 'Не реализован')], default='В процессе', max_length=20, verbose_name='Выберите Статус'),
        ),
    ]
