# Generated by Django 4.0.8 on 2022-11-01 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contests_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='Status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Проведён', 'Проведён'), ('Не Проведён', 'Не Проведён')], default='В процессе', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='news',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.projectcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Кыргызча', 'Кыргызча'), ('English', 'English'), ('中国人', '中国人')], default='Русский', max_length=10, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Status',
            field=models.CharField(choices=[('В процессе', 'В процессе'), ('Реализован', 'Реализован'), ('Не реализован', 'Не реализован')], default='В процессе', max_length=20, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
