# Generated by Django 4.0.8 on 2022-10-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_contests_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoscontests',
            name='Gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerycontests', verbose_name='Галерея'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='Gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='main.gallerynews', verbose_name='Галерея'),
        ),
    ]
