# Generated by Django 4.0.8 on 2022-11-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contests_language_alter_contests_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Short_Description',
            field=models.CharField(max_length=110, verbose_name='Краткое описание'),
        ),
    ]
