# Generated by Django 4.0.8 on 2022-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_news_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoscontests',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='photosnews',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='photosproject',
            name='Title',
        ),
        migrations.AddField(
            model_name='photoscontests',
            name='Caption',
            field=models.CharField(default='', max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AddField(
            model_name='photosnews',
            name='Caption',
            field=models.CharField(default='', max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AddField(
            model_name='photosproject',
            name='Caption',
            field=models.CharField(default='', max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AlterField(
            model_name='photosproject',
            name='URL',
            field=models.FileField(upload_to='', verbose_name='Путь к картинке'),
        ),
    ]
