# Generated by Django 4.0.8 on 2022-11-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_photoscontests_title_remove_photosnews_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosproject',
            name='URL',
            field=models.FileField(upload_to='client/img/news/', verbose_name='Путь к картинке'),
        ),
    ]
