# Generated by Django 4.0.8 on 2022-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_photosnews_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosnews',
            name='URL',
            field=models.FileField(upload_to='client/img/news/', verbose_name='Путь картинки'),
        ),
    ]
