# Generated by Django 4.0.8 on 2022-11-10 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_photosnews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosnews',
            name='Caption',
            field=models.CharField(max_length=70, verbose_name='Название картинки'),
        ),
        migrations.AlterField(
            model_name='photosnews',
            name='URL',
            field=models.FileField(upload_to='static/client/img/news/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Путь картинки'),
        ),
    ]
