# Generated by Django 4.0.8 on 2022-11-11 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_photosnews_caption_alter_photosnews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosnews',
            name='URL',
            field=models.ImageField(upload_to='static/client/img/news/', validators=[django.core.validators.validate_image_file_extension], verbose_name='Путь картинки'),
        ),
    ]
